export const FETCHING_USERS_BEGIN = "FETCHING_USERS_BEGIN";
export const FETCHED_USERS_SUCCESSFULLY = "FETCHED_USERS_SUCCESSFULLY";
export const FETCHING_USERS_FAILURE = "FETCHING_USERS_FAILURE";
export const SET_NATIONALITY = "SET_NATIONALITY";
export const SELECT_USER = "SELECT_USER";
export const UNSELECT_USER = "UNSELECT_USER";
export const CACHED_USER = "CACHED_USER";
export const TOTAL_RECORDS = 200;
